import { IDomainEvent } from "../../shared/domain/BaseDomainEvent";

/**
 * IConversationEventStore represents the event store interface contract.
 */
export interface IConversationEventStore {
  /**
   * Saves a domain event generated by a conversation aggregate.
   */
  saveEvent(event: IDomainEvent, correlationId: string): Promise<void>;

  /**
   * Saves multiple domain events in a single transaction.
   */
  saveEvents(events: IDomainEvent[], correlationId: string): Promise<void>;

  /**
   * Loads all events registered for a conversation.
   */
  getEventsByConversationId(conversationId: string): Promise<IDomainEvent[]>;
}
