import { useCallback, useEffect, useState } from 'react';
import { Moon, RefreshCw, Send, Server, Sliders, Sun, ArrowRight } from 'lucide-react';
import { useTheme } from '../theme/themeProvider';
import { Button, InlineAlert, PageHeader, Section, StatusBadge } from '../components/ui/Primitives';

interface SettingsProps {
  apiBaseUrl: string;
  onNavigate?: (tab: any) => void;
}

export function Settings({ apiBaseUrl, onNavigate }: SettingsProps) {
  const { theme, setTheme } = useTheme();
  const [health, setHealth] = useState<'checking' | 'available' | 'unavailable'>('checking');
  const [checkedAt, setCheckedAt] = useState<Date | null>(null);
  const check = useCallback(async () => { setHealth('checking'); try { const response = await fetch(`${apiBaseUrl}/health`); setHealth(response.ok ? 'available' : 'unavailable'); } catch { setHealth('unavailable'); } finally { setCheckedAt(new Date()); } }, [apiBaseUrl]);
  useEffect(() => { check(); }, [check]);

  return <div className="page-scroll space-y-6"><PageHeader eyebrow="Configuration" title="Settings" description="Functional preferences are separated from read-only runtime information and controls that do not yet have persistence contracts." />
    <InlineAlert tone="information" title="Configuration boundary">This frontend currently exposes no authenticated settings-write endpoint. Non-functional controls are shown as read-only or planned and never report a false save.</InlineAlert>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-5"><Section><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Server className="h-4 w-4 text-primary" /><h2 className="font-bold">API environment</h2></div><p className="mt-1 text-sm text-muted-foreground">Read-only values derived from the running frontend environment.</p></div><StatusBadge tone={health === 'available' ? 'success' : health === 'unavailable' ? 'error' : 'pending'}>{health === 'checking' ? 'Checking' : health === 'available' ? 'Reachable' : 'Unavailable'}</StatusBadge></div><dl className="mt-5 divide-y divide-border rounded-xl border border-border"><div className="grid gap-1 p-3 sm:grid-cols-[10rem_1fr]"><dt className="text-sm text-muted-foreground">Backend base URL</dt><dd className="break-all font-mono text-sm">{apiBaseUrl}</dd></div><div className="grid gap-1 p-3 sm:grid-cols-[10rem_1fr]"><dt className="text-sm text-muted-foreground">Last health check</dt><dd className="text-sm font-semibold">{checkedAt?.toLocaleString() || 'Not checked'}</dd></div><div className="grid gap-1 p-3 sm:grid-cols-[10rem_1fr]"><dt className="text-sm text-muted-foreground">Database provider</dt><dd className="text-sm font-semibold text-unavailable">Not exposed by frontend API</dd></div></dl><Button variant="secondary" className="mt-4" onClick={check} disabled={health === 'checking'}><RefreshCw className={`h-4 w-4 ${health === 'checking' ? 'animate-spin' : ''}`} />Check connection</Button></Section>
      <Section><div className="flex items-center gap-2"><Sliders className="h-4 w-4 text-primary" /><h2 className="font-bold">Operational policy</h2></div><p className="mt-1 text-sm text-muted-foreground">The values below are controlled elsewhere in the runtime and cannot be changed safely here.</p><fieldset disabled className="mt-5 space-y-4"><label className="block"><span className="text-sm font-semibold">Conversation refresh interval</span><span className="mt-1 block text-xs text-muted-foreground">Read-only · current frontend implementation</span><input className="field-control mt-2 w-full" value="30 seconds" readOnly /></label><label className="block"><span className="text-sm font-semibold">Human takeover lease</span><span className="mt-1 block text-xs text-muted-foreground">Not connected · requires backend policy contract</span><input className="field-control mt-2 w-full" value="Runtime managed" readOnly /></label><label className="block"><span className="text-sm font-semibold">Handoff sound preference</span><span className="mt-1 block text-xs text-muted-foreground">Planned · no persistent preference exists</span><input className="field-control mt-2 w-full" value="Unavailable" readOnly /></label></fieldset></Section></div>
      <div className="space-y-5"><Section><div className="flex items-center gap-2">{theme === 'light' ? <Sun className="h-4 w-4 text-primary" /> : <Moon className="h-4 w-4 text-primary" />}<h2 className="font-bold">Theme preference</h2><StatusBadge tone="success">Functional · persisted locally</StatusBadge></div><p className="mt-1 text-sm text-muted-foreground">Choose the workspace theme. The preference is stored in this browser.</p><div className="mt-5 grid grid-cols-2 gap-2" role="group" aria-label="Theme preference"><button type="button" aria-pressed={theme === 'light'} onClick={() => setTheme('light')} className={`touch-target flex items-center justify-center gap-2 rounded-lg border px-3 text-sm font-semibold ${theme === 'light' ? 'border-primary bg-primary/10 text-primary' : 'border-border'}`}><Sun className="h-4 w-4" />Light</button><button type="button" aria-pressed={theme === 'dark'} onClick={() => setTheme('dark')} className={`touch-target flex items-center justify-center gap-2 rounded-lg border px-3 text-sm font-semibold ${theme === 'dark' ? 'border-primary bg-primary/10 text-primary' : 'border-border'}`}><Moon className="h-4 w-4" />Dark</button></div></Section>
      <Section><h2 className="font-bold">Integrations</h2><p className="mt-1 text-sm text-muted-foreground">Manage multi-project workspace mappings and external ticketing systems.</p><div className="mt-5 space-y-3"><div className="flex items-center justify-between gap-3 rounded-lg border border-border p-3"><div><p className="text-sm font-semibold">PromptX / MCP</p><p className="text-xs text-muted-foreground">Connection state not exposed</p></div><StatusBadge tone="unavailable">Unknown</StatusBadge></div><div className="flex items-center justify-between gap-3 rounded-lg border border-border p-3"><div><p className="text-sm font-semibold">Plane.so Project Integrations</p><p className="text-xs text-muted-foreground">Multi-project workspace routing center</p></div>{onNavigate ? <Button variant="secondary" onClick={() => onNavigate('plane-integrations')} className="flex items-center gap-1.5 text-xs text-primary"><Send className="h-3.5 w-3.5 rotate-[-20deg]" />Manage Plane</Button> : <StatusBadge tone="information">Configured</StatusBadge>}</div></div></Section></div>
    </div>
  </div>;
}
