import { BaseRepository } from "../../shared/repositories/BaseRepository";
import { IConversationEventStore } from "../../domain/repositories/IConversationEventStore";
import { IDomainEvent } from "../../shared/domain/BaseDomainEvent";
import { TransactionManager } from "../../shared/repositories/TransactionManager";

/**
 * PostgresConversationEventStore implements IConversationEventStore
 * storing aggregate domain events in PostgreSQL.
 */
export class PostgresConversationEventStore
  extends BaseRepository<any, string>
  implements IConversationEventStore
{
  constructor(transactionManager: TransactionManager) {
    super(transactionManager);
  }

  async findById(id: string): Promise<any | null> {
    return null;
  }

  async save(entity: any): Promise<any> {
    return entity;
  }

  /**
   * Saves a domain event generated by a conversation aggregate.
   */
  async saveEvent(event: IDomainEvent, correlationId: string): Promise<void> {
    const conversationId = parseInt(event.getAggregateId(), 10);
    if (isNaN(conversationId)) {
      throw new Error(
        `[EventStore] Conversation ID must be a valid integer: ${event.getAggregateId()}`
      );
    }

    const eventType = event.constructor.name;
    const payload = JSON.stringify(event);

    await this.db.query(
      `INSERT INTO conversation_events (conversation_id, event_type, payload, correlation_id, created_at)
       VALUES ($1, $2, $3, $4, $5)`,
      [conversationId, eventType, payload, correlationId, event.occurredAt]
    );
  }

  /**
   * Saves multiple domain events in a single transaction.
   */
  async saveEvents(events: IDomainEvent[], correlationId: string): Promise<void> {
    for (const event of events) {
      await this.saveEvent(event, correlationId);
    }
  }

  /**
   * Loads all events registered for a conversation.
   */
  async getEventsByConversationId(conversationId: string): Promise<IDomainEvent[]> {
    const convId = parseInt(conversationId, 10);
    if (isNaN(convId)) {
      throw new Error(`[EventStore] Conversation ID must be a valid integer: ${conversationId}`);
    }

    const { rows } = await this.db.query(
      `SELECT event_type, payload, created_at FROM conversation_events
       WHERE conversation_id = $1
       ORDER BY created_at ASC`,
      [convId]
    );

    return rows.map((row) => {
      const payloadObj =
        typeof row.payload === "string" ? JSON.parse(row.payload) : row.payload;
      return {
        occurredAt: new Date(row.created_at),
        getAggregateId: () => conversationId,
        eventType: row.event_type,
        ...payloadObj,
      };
    });
  }
}
